name: Deploy and Update LMSS Application

on:
  push:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Frontend to Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend:latest

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend to Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend:latest

  deploy-frontend:
    needs: frontend-build
    runs-on: [self-hosted, frontend]
    steps:
      - name: Pull frontend image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend:latest

      - name: Delete old frontend container
        run: docker rm -f lmss-frontend-container || true

      - name: Run frontend container
        run: docker run -d -p 3000:3000 --name lmss-frontend-container ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend:latest

  deploy-backend:
    needs: backend-build
    runs-on: [self-hosted, backend]
    steps:
      - name: Pull backend image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend:latest

      - name: Delete old backend container
        run: docker rm -f lmss-backend-container || true

      - name: Run backend container
        run: docker run -d -p 4000:4000 --name lmss-backend-container ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend:latest
