name: Deploy LMSS to Azure via Docker Hub

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lmss-frontend

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lmss-backend
